var str = "abcdeabcde";
console.log("str:", str);
console.log("str.charAt(0):", str.charAt(0));
console.log("str[1]:", str[1]);
console.log("str.length:", str.length);
console.log("str.charAt(-1):", str.charAt(-1));
console.log("str.substring(2, 4):", str.substring(2, 4));
console.log("str.substr(2, 4):", str.substr(2, 4));
console.log("str.indexOf(\"bc\"):", str.indexOf("bc"));
console.log("str.lastIndexOf(\"bc\"):", str.lastIndexOf("bc"));
